---
title: "Lab Exercise 2"
output: html_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product1 <- data.frame()

for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/Lugz-Mens-Clipper-Sneaker-White/product-reviews/B07PML31RC/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Lugz Men's Clipper Classic Slip-On Fashion Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product1 <- rbind(Product1, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product1)
``` 

```{r}
Product2 <- data.frame()

for (page in 1:5) {
  link2 <- paste0("https://www.amazon.com.au/Skechers-Afterburn-fashion-sneakers-Black/product-reviews/B00D881KE6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session2 <- bow(link2, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Skechers Men's Afterburn M. Fit"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product2 <- rbind(Product2, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product2)
```

```{r}

Product3 <- data.frame()

for (page in 1:5) {
  link3 <- paste0("https://www.amazon.com.au/Skechers-Womens-33492-Sneaker-Olive/product-reviews/B08PDTS2RG/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session3 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Skechers Women's BOBS B Cute Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product3 <- rbind(Product3, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product3)
```

```{r}

Product4 <- data.frame()

for (page in 1:5) {
  link4 <- paste0("https://www.amazon.com.au/Clarks-Womens-Emslie-Warren-Leather/product-reviews/B01N2TBSOE/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session4 <- bow(link4, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Clarks Women's Emslie Warren Slip-On Loafer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product4 <- rbind(Product4, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product4)
```

```{r}

Product5 <- data.frame()

for (page in 1:5) {
  link5 <- paste0("https://www.amazon.com.au/PUMA-Mens-Tazon-Sneaker-Black/product-reviews/B07TMTFKCF/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session5 <- bow(link5, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "PUMA Men's Tazon 6 Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product5 <- rbind(Product5, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product5)
```

```{r}

Product6 <- data.frame()

for (page in 1:5) {
  link6 <- paste0("https://www.amazon.com.au/Skechers-Afterburn-Wonted-Loafer-pebble/product-reviews/B075PF4PMC/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session6 <- bow(link6, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Skechers Men's Afterburn M. Fit Wonted Loafer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product6 <- rbind(Product6, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product6)
```

```{r}

Product7 <- data.frame()

for (page in 1:5) {
  link7 <- paste0("https://www.amazon.com.au/DREAM-PAIRS-Womens-Annee-Black/product-reviews/B071R2CVLV/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session7 <- bow(link7, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "DREAM PAIRS ANNEE Pointed Toe Low Chunky Heels Pump Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product7 <- rbind(Product7, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product7)
```

```{r}

Product8 <- data.frame()

for (page in 1:5) {
  link8 <- paste0("https://www.amazon.com.au/Skechers-Womens-5-15901-Black-White/product-reviews/B07N13VNG4/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session8 <- bow(link8, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Skechers Women's Go Walk 5"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product8 <- rbind(Product8, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product8)
```

```{r}

Product9 <- data.frame()

for (page in 1:5) {
  link9 <- paste0("https://www.amazon.com.au/Skechers-Moreno-Canvas-Oxford-Beige/product-reviews/B07J5TJDKP/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session9 <- bow(link9, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Skechers Men's Moreno Canvas Oxford Shoe"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product9 <- rbind(Product9, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product9)
```

```{r}

Product10 <- data.frame()

for (page in 1:5) {
  link10 <- paste0("https://www.amazon.com.au/Under-Armour-Charged-Assert-Black/product-reviews/B087TGZQRZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session10 <- bow(link10, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Under Armour Men's Charged Assert 9 Running Shoe"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product10 <- rbind(Product10, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product10)
```

```{r}

Product11 <- data.frame()

for (page in 1:5) {
  link11 <- paste0("https://www.amazon.com.au/Amazon-Essentials-Womens-Loafer-Flat/product-reviews/B088KBY4C6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session11 <- bow(link11, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session11) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Amazon Essentials Women's Loafer Flat"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product11 <- rbind(Product11, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product11)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product12 <- data.frame()

for (page in 1:5) {
  link12 <- paste0("https://www.amazon.com.au/PRINCE-Classic-Modern-Wingtip-PRINCE-3-BLACK/product-reviews/B00SX5K49Q/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session12 <- bow(link12, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session12) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Bruno Moda Italy Men's Prince Classic Modern Formal Oxford Wingtip Lace Up Dress Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product12 <- rbind(Product12, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 Sys.sleep(3)
}

View(Product12)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product13 <- data.frame()

for (page in 1:5) {
  link13 <- paste0("https://www.amazon.com.au/PUMA-Womens-Sneaker-White-Gulf-Stream/product-reviews/B07TKWZHNQ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session13 <- bow(link13, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session13) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "PUMA Women's Riaze Prowl Running Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product13 <- rbind(Product13, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product13)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product14 <- data.frame()

for (page in 1:5) {
  link14 <- paste0("https://www.amazon.com.au/Reebok-Womens-Princess-Walking-White/product-reviews/B06XWFRNPZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session14 <- bow(link14, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session14) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Reebok Women's Princess Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product14 <- rbind(Product14, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product14)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product15 <- data.frame()

for (page in 1:5) {
  link15 <- paste0("https://www.amazon.com.au/DREAM-PAIRS-Womens-LUVLY-W-Closed/product-reviews/B0BQ2WJ9J6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session15 <- bow(link15, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session15) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "DREAM PAIRS Women's Luvly Bridal Wedding Party Low Heel Pump Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product15 <- rbind(Product15, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product15)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product16 <- data.frame()

for (page in 1:5) {
  link16 <- paste0("https://www.amazon.com.au/CLARKS-Womens-Ashland-Slip-Loafer/product-reviews/B00U8PORZ6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session16 <- bow(link16, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session16) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Clarks Women's Ashland Lane Q Slip-On Loafer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product16 <- rbind(Product16, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product16)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product17 <- data.frame()

for (page in 1:5) {
  link17 <- paste0("https://www.amazon.com.au/WHITIN-Running-Minimalist-Barefoot-Comfortable/product-reviews/B09F69MPZR/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session17 <- bow(link17, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session17) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "WHITIN Men's Cross-Trainer | Barefoot & Minimalist Shoe | Zero Drop Sole | Wide Toe Box"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product17 <- rbind(Product17, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product17)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product18 <- data.frame()

for (page in 1:5) {
  link18 <- paste0("https://www.amazon.com.au/Skechers-Performance-Womens-Walking-white/product-reviews/B071WV29CK/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session18 <- bow(link18, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session18) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Skechers Women's Go Walk Joy Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product18 <- rbind(Product18, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product18)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product19 <- data.frame()

for (page in 1:5) {
  link19 <- paste0("https://www.amazon.com.au/Clarks-Mens-Tilden-Oxford-Leather/product-reviews/B01N2SBKU9/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session19 <- bow(link19, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session19) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Clarks Men's Tilden Cap Oxford"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product19 <- rbind(Product19, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product19)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product20 <- data.frame()

for (page in 1:5) {
  link20 <- paste0("https://www.amazon.com.au/Vans-Atwood-Textile-Shoes-Black/product-reviews/B0081H9AAU/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session20 <- bow(link20, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session20) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Vans Men's Atwood Low-top Sneaker"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product20 <- rbind(Product20, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product20)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product21 <- data.frame()

for (page in 1:5) {
  link21 <- paste0("https://www.amazon.com.au/Skechers-Nampa-Service-black-polyurethane/product-reviews/B077811KQL/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session21 <- bow(link21, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session21) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Skechers Men's Nampa Food Service Shoe"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product21 <- rbind(Product21, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product21)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product22 <- data.frame()

for (page in 1:5) {
  link22 <- paste0("https://www.amazon.com.au/Brooks-Womens-Adrenaline-Supportive-Running/product-reviews/B0BHKSPGXG/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session22 <- bow(link22, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session22) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Brooks Women's Adrenaline GTS 22 Supportive Running Shoe"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product22 <- rbind(Product22, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product22)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product23 <- data.frame()

for (page in 1:5) {
  link23 <- paste0("https://www.amazon.com.au/Amazon-Essentials-Womens-Ballet-Snake/product-reviews/B088KDZ4TR/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session23 <- bow(link23, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session23) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Amazon Essentials Women's Belice Ballet Flat"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product23 <- rbind(Product23, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product23)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product24 <- data.frame()

for (page in 1:5) {
  link24 <- paste0("https://www.amazon.com.au/DREAM-PAIRS-Sole_Stretchy-Fashion-Elastic/product-reviews/B078PXVPYB/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session24 <- bow(link24, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session24) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "DREAM PAIRS Women's Comfortable Fashion Elastic Ankle Straps Flats Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product24 <- rbind(Product24, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product24)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product25 <- data.frame()

for (page in 1:5) {
  link25 <- paste0("https://www.amazon.com.au/Obtaom-Womens-Fashion-Sneaker-Leopard/product-reviews/B08NJJPSBM/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session25 <- bow(link25, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session25) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Obtaom Women's Play Fashion Sneaker White Color Washed and Leopard Canvas Slip on Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product25 <- rbind(Product25, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product25)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product26 <- data.frame()

for (page in 1:5) {
  link26 <- paste0("https://www.amazon.com.au/Hey-Dude-Womens-Wendy-Crochet/product-reviews/B08MGVHSYG/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session26 <- bow(link26, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session26) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Hey Dude Women's Wendy Boho Slip-on Casual Shoes Loafer, 6 US"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product26 <- rbind(Product26, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product26)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product27 <- data.frame()

for (page in 1:5) {
  link27 <- paste0("https://www.amazon.com.au/DREAM-PAIRS-Womens-Sandals-Carnival/product-reviews/B082B3K4MT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session27<- bow(link27, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session27) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "DREAM PAIRS Women's Open Toe Ankle Strap Low Block Chunky Heels Sandals Party Dress Pumps Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product27 <- rbind(Product27, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product27)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product28 <- data.frame()

for (page in 1:5) {
  link28 <- paste0("https://www.amazon.com.au/WHITIN-Running-Minimalist-Barefoot-Lightweight/product-reviews/B09F699SQZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session28<- bow(link28, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session28) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "WHITIN Men's Cross-Trainer | Barefoot & Minimalist Shoe | Zero Drop Sole | Wide Toe Box"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product28 <- rbind(Product28, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product28)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product29 <- data.frame()

for (page in 1:5) {
  link29 <- paste0("https://www.amazon.com.au/Nike-Monarch-Running-Metallic-Silver/product-reviews/B004IM5K1K/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session29<- bow(link29, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session29) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Nike Men's Air Monarch Iv Cross Trainer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product29 <- rbind(Product29, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product29)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product30 <- data.frame()

for (page in 1:5) {
  link30 <- paste0("https://www.amazon.com.au/Bruno-RIVERA-01-Oxfords-Shoes-Sneakers/product-reviews/B01N3MAX21/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session30<- bow(link30, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session30) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Bruno Marc Men's Rivera Oxfords Shoes Sneakers"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product30 <- rbind(Product30, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product30)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product31 <- data.frame()

for (page in 1:5) {
  link31 <- paste0("https://www.amazon.com.au/Clarks-Ashland-Bubble-Womens-Black/product-reviews/B00DXNV6AO/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session31<- bow(link31, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session31) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Clarks Women's, Ashland Bubble Loafer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product31 <- rbind(Product31, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product31)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product32 <- data.frame()

for (page in 1:5) {
  link32 <- paste0("https://www.amazon.com.au/Skechers-Performance-Womens-Walk-Lite-15433/product-reviews/B072NDVRR4/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session32<- bow(link32, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session32) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Skechers Women's Go Walk Lite-15433 Boat Shoe"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product32 <- rbind(Product32, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product32)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product33 <- data.frame()

for (page in 1:5) {
  link33 <- paste0("https://www.amazon.com.au/DREAM-PAIRS-Womens-Revona-Suede/product-reviews/B073H72KBS/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session33<- bow(link33, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session33) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "DREAM PAIRS Women's Revona Low Wedge Ankle Strap Flats Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product33<- rbind(Product33, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product33)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product34 <- data.frame()

for (page in 1:5) {
  link34 <- paste0("https://www.amazon.com.au/YDB-Lightweight-Breathable-Athletic-Sneakers/product-reviews/B08FR6G1M4/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session34<- bow(link34, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session34) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "VAMJAM Men's Running Shoes Ultra Lightweight Breathable Walking Shoes Non Slip Athletic Fashion Sneakers Mesh Workout Casual Sports Shoes"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product34<- rbind(Product34, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product34)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Product35 <- data.frame()

for (page in 1:5) {
  link35 <- paste0("https://www.amazon.com.au/Kizik-Madrid-Eco-Knit-Sneakers-Casual/product-reviews/B08MV86X1T/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session35<- bow(link35, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session35) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Kizik Madrid Comfortable Breathable Eco-Knit Slip On Sneakers - Easy Slip-Ons | Walking Shoes for Men, Women and Elderly | Stylish, Convenient and Orthopedic Shoes for Athleisure and Travel"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Product35<- rbind(Product35, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  Sys.sleep(3)
}

View(Product35)
```